for j in *.txt;do #For all mapping results generated by KofamScan
	genome_name=${j%_res.txt}; #Keep the genome name
	pre="LOCUSTAG"; #The default prefix of each protein is LOCUSTAG
	sed -i "s/${pre}/${tmp}/g" $j; #Subsititute the protein prefix from "LOCUSTAG" to genome name
	grep ^* $j >> allMTB.kofam.sig.txt; #Save all significant mapped genes into one txt file
done